name: packages


on:
  repository_dispatch:
  push:
    branches: 
      - src
    paths:
      - '.github/workflows/packages.yml'
      - 'packages.seed'
      - '*.sh'
  pull_request:
    branches:
      - src
  schedule:
    - cron: '0 17 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
          
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: src
          fetch-depth: 0

      - name: Save Private Key
        if: github.event_name == 'push'
        run: |
          echo 'untrusted comment: private key 5e99c2573f29d764' > private.key
          echo "${{ secrets.private_key }}" >> private.key

      - name: Init Env
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          . init_env.sh
      
      - name: Friendlywrt Source
        run: |
          . friendlywrt_source.sh

      - name: Change Feeds to Lean
        run: |
          cd friendlywrt-rk3328
          git clone https://github.com/coolsnowwolf/lede
          cd friendlywrt
          cp -r ../lede/package/lean package/
          sed -i 's/^src-git luci.*/src-git luci https:\/\/github.com\/coolsnowwolf\/luci/' feeds.conf.default
          sed -i 's/^src-git packages.*/src-git packages https:\/\/github.com\/coolsnowwolf\/packages/' feeds.conf.default
        
      - name: Add Packages to Lean
        run: |
          . add_packages_to_lean.sh

      - name: Install Openwrt Libs
        run: |
          git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"
          cd friendlywrt-rk3328
          git clone https://github.com/openwrt/openwrt
          rm -rf friendlywrt/package/libs
          cp -r openwrt/package/libs friendlywrt/package/
      
      - name: Use Chuck's Kernel
        run: |
          cd friendlywrt-rk3328
          rm -rf kernel
          git clone --depth=1 https://github.com/fanck0605/friendlywrt-kernel.git kernel
          cd openwrt
          ./scripts/patch-kernel.sh ../kernel target/linux/generic/backport-5.4
          ./scripts/patch-kernel.sh ../kernel target/linux/generic/pending-5.4
          ./scripts/patch-kernel.sh ../kernel target/linux/generic/hack-5.4
          ./scripts/patch-kernel.sh ../kernel target/linux/octeontx/patches-5.4
          cp -a ./target/linux/generic/files/* ../kernel/
          cd ../kernel
          wget -O net/netfilter/xt_FULLCONENAT.c https://raw.githubusercontent.com/Chion82/netfilter-full-cone-nat/master/xt_FULLCONENAT.c
          wget -O ../fullcone_nat.patch https://github.com/fanck0605/nanopi-r2s/raw/openwrt-lienol/patches/001-kernel-add-full_cone_nat.patch
          git apply ../fullcone_nat.patch

      - name: Update Feeds
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Install UPX
        run: |
          mkdir -p friendlywrt-rk3328/friendlywrt/staging_dir/host/bin/
          ln -s /usr/bin/upx-ucl friendlywrt-rk3328/friendlywrt/staging_dir/host/bin/upx
  
      - name: Update Target.mk
        run: |
          cd friendlywrt-rk3328/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk

      - name: Build Config
        run: |
          cd friendlywrt-rk3328
          cat configs/config_rk3328 | grep "TARGET" > ../rk3328.config
          cat ../packages.seed >> ../rk3328.config
          cat ../rk3328.config > configs/config_rk3328
          cat configs/config_rk3328
      
      - name: Clean src
        run: |
          cd friendlywrt-rk3328
          rm -rf lede
          rm -rf openwrt

      - name: Add usign
        run: |
          mkdir -p friendlywrt-rk3328/friendlywrt/staging_dir/host/bin/
          sudo chmod a+x usign
          cp usign friendlywrt-rk3328/friendlywrt/staging_dir/host/bin/
          sudo mv usign /usr/bin/

      - name: Build Friendlywrt
        env:
          IGNORE_ERRORS: 1
        run: |
          cd friendlywrt-rk3328
          ./build.sh nanopi_r2s.mk
    
      - name: Collect Packages
        run: |
          cd friendlywrt-rk3328
          mkdir -p packagerepo/packages
          mv friendlywrt/bin/packages/aarch64_cortex-a53/*/*.ipk packagerepo/packages/
          mv friendlywrt/bin/targets/rockchip-rk3328/generic/packages/*.ipk packagerepo/packages/
          cat -s friendlywrt/bin/packages/aarch64_cortex-a53/*/Packages > packagerepo/packages/Packages
          cat -s friendlywrt/bin/targets/rockchip-rk3328/generic/packages/Packages >> packagerepo/packages/Packages
          cat -s friendlywrt/bin/packages/aarch64_cortex-a53/*/Packages.manifest > packagerepo/packages/Packages.manifest
          cat -s friendlywrt/bin/targets/rockchip-rk3328/generic/packages/Packages.manifest >> packagerepo/packages/Packages.manifest
          cd packagerepo/packages/
          gzip -k Packages
          ls *.ipk
      
      - name: Sign Packages
        if: github.event_name == 'push'
        run: |
          cd friendlywrt-rk3328
          cd packagerepo/packages
          usign -S -m Packages -s ../../../private.key -x Packages.sig

      - name: Push Changes
        if: github.event_name == 'push'
        run: |
          cd friendlywrt-rk3328/packagerepo
          mkdir keys
          cp ../../keys/* keys/
          cp ../../README.md ./
          cp ../../README.md ./packages/
          cp ../../CNAME ./
          git init
          git add .
          git commit -m "Depoly at $(date +%Y-%m-%d)"
          git push -f "https://${{ secrets.sec_token }}@github.com/songchenwen/nanopi-r2s-opkg-feeds.git" master:master
